// scripts/copy-drawio.mjs
// Copies drawio 31.4.6 source into server/public/drawio/ and patches
// PreConfig.js / PostConfig.js / bootstrap.js for offline, internal deployment.

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SRC = 'C:/Users/shaoqisun/Desktop/drawio-31.4.6/src/main/webapp'
const DST = join(ROOT, 'server/public/drawio')

// 1. Wipe target
rmSync(DST, { recursive: true, force: true })
mkdirSync(DST, { recursive: true })

function copyDir(srcSub, dstSub) {
  const src = join(SRC, srcSub)
  const dst = join(DST, dstSub)
  if (!existsSync(src)) {
    console.warn(`[copy-drawio] skip missing: ${srcSub}`)
    return
  }
  cpSync(src, dst, { recursive: true })
  console.log(`[copy-drawio] copied: ${srcSub}`)
}

// 2. Copy the runtime-needed subtrees
copyDir('js/app.min.js', 'js/app.min.js')
copyDir('js/extensions.min.js', 'js/extensions.min.js')
copyDir('js/stencils.min.js', 'js/stencils.min.js')
copyDir('js/shapes-14-6-5.min.js', 'js/shapes-14-6-5.min.js')
copyDir('js/bootstrap.js', 'js/bootstrap.js')
copyDir('js/plantuml', 'js/plantuml')
copyDir('mxgraph', 'mxgraph')
copyDir('styles', 'styles')
copyDir('resources', 'resources')
copyDir('templates', 'templates')
copyDir('img', 'img')
copyDir('images', 'images')

// 3. Write custom PreConfig.js (overwrites the copied one)
const preConfig = `/**
 * WeDraw self-host PreConfig — nulls all remote endpoints, sets paths to /drawio/*.
 * Generated by scripts/copy-drawio.mjs; do not edit by hand.
 */
window.DRAWIO_PUBLIC_BUILD = true;

// Block all ServiceWorker registration. drawio 31.4.6 tries to register
// /drawio/service-worker.js (or fetch the existing one), which would either
// 404 in our self-hosted setup or pollute the user's browser cache. Replace
// the registration API with a no-op so App.main's service worker code path
// silently bails out.
if ('serviceWorker' in navigator) {
  Object.defineProperty(navigator, 'serviceWorker', {
    value: {
      register: function () { return Promise.reject(new Error('ServiceWorker disabled in WeDraw self-host')); },
      getRegistration: function () { return Promise.resolve(null); },
      getRegistrations: function () { return Promise.resolve([]); },
      ready: Promise.reject(new Error('ServiceWorker disabled in WeDraw self-host')),
    },
    configurable: true,
  });
}

// Null every remote endpoint so drawio never talks to drawio.com / convert.diagrams.net
window.EXPORT_URL = null;
window.DRAWIO_BASE_URL = null;
window.DRAWIO_VIEWER_URL = null;
window.DRAWIO_LIGHTBOX_URL = null;
window.DRAW_MATH_URL = null;
window.VSS_CONVERT_URL = null;
window.RT_WEBSOCKET_URL = null;
window.REALTIME_URL = null;
window.DRAWIO_GITHUB_URL = null;
window.DRAWIO_GITHUB_API_URL = null;
window.DRAWIO_GITHUB_ID = null;
window.DRAWIO_GITLAB_URL = null;
window.DRAWIO_GITLAB_ID = null;
window.DRAWIO_DROPBOX_ID = null;
window.SAVE_URL = null;
window.PROXY_URL = null;
window.NOTIFICATIONS_URL = null;
window.PUSHER_URL = null;

// Absolute paths so drawio fetches everything from our backend
window.STYLE_PATH = '/drawio/styles';
window.CSS_PATH  = '/drawio/styles';
window.OPEN_FORM = '/drawio/open.html';
window.mxBasePath = '/drawio/mxgraph';
window.mxImageBasePath = '/drawio/mxgraph/images';
window.RESOURCES_PATH = '/drawio/resources';
window.RESOURCE_BASE = '/drawio/resources/dia';
window.SHAPES_PATH = '/drawio/shapes';
window.GRAPH_IMAGE_PATH = '/drawio/img';
window.TEMPLATE_PATH = '/drawio/templates';
window.STENCIL_PATH = '/drawio/stencils';
window.PLUGINS_BASE_PATH = '/drawio';

window.urlParams = window.urlParams || {};
urlParams['sync'] = 'manual';          // disable autosave roundtrip
urlParams['offline'] = '1';            // disables db/od/gh/gl/tr/gapi/picker/Pusher/plugins
urlParams['math'] = '0';               // skip MathJax
urlParams['libraries'] = '0';          // hide More Shapes
urlParams['saveAndExit'] = '0';
urlParams['noExitBtn'] = '1';
urlParams['noSaveBtn'] = '1';
urlParams['lang'] = 'zh';              // force Chinese UI
urlParams['ui'] = 'simple';            // force Draw.io's simple UI theme
urlParams['tabs'] = '0';               // hide page tabs
urlParams['grid'] = '0';               // hide grid by default
urlParams['pv'] = '0';                 // disable page view
urlParams['noHelpBtn'] = '1';          // hide help button
urlParams['noStatusBtn'] = '1';        // hide status button
urlParams['noFullScreen'] = '1';       // hide fullscreen button
`
writeFileSync(join(DST, 'js/PreConfig.js'), preConfig, 'utf8')
console.log('[copy-drawio] wrote: js/PreConfig.js (patched)')

// 4. Write custom PostConfig.js (overwrites the copied one)
const postConfig = `/**
 * WeDraw self-host PostConfig — runs after app.min.js loads.
 * Generated by scripts/copy-drawio.mjs; do not edit by hand.
 */
window.ICONSEARCH_PATH = null;
window.ICON_SERVICE_PATH = null;
if (typeof window.App !== 'undefined') {
  try {
    window.App.TRELLO_URL = '';
    window.App.PUSHER_URL = '';
    window.App.SIMPLE_PEER_URL = '';
    window.App.DROPBOX_URL = '';
    window.App.DROPINS_URL = '';
    window.App.ONEDRIVE_URL = '';
  } catch (e) { /* App may not expose all of these */ }
}
`
writeFileSync(join(DST, 'js/PostConfig.js'), postConfig, 'utf8')
console.log('[copy-drawio] wrote: js/PostConfig.js (patched)')

// 5. Patch bootstrap.js:
//    a) App.main(); → App.main(window.onDrawioAppReady);
//    b) Insert `mxWinLoaded = true;` before `checkAllLoaded();` so the
//       production onload chain (PreConfig → app.min.js → ... → PostConfig)
//       unblocks even though we never load drawio's standalone main.js
//       (which is what normally sets mxWinLoaded on window.load).
const bootstrapPath = join(DST, 'js/bootstrap.js')
const bootstrap = readFileSync(bootstrapPath, 'utf8')

const targets = [
  {
    needle: '        App.main();\t\t\t\t',
    replacement: '        App.main(window.onDrawioAppReady, window.wedrawCreateAppUi);\t',
    label: 'App.main → App.main(window.onDrawioAppReady, window.wedrawCreateAppUi)',
  },
  {
    // In loadAppJS's onload for app.min.js, the snippet is:
    //   mxScriptsLoaded = true;
    //   checkAllLoaded();
    // We prepend mxWinLoaded = true; so checkAllLoaded's `&& mxWinLoaded`
    // gate passes. (Indent matches the 16-space indent inside mxscript callback.)
    needle: '                mxScriptsLoaded = true;\n                checkAllLoaded();',
    replacement: '                mxScriptsLoaded = true;\n                mxWinLoaded = true;\n                checkAllLoaded();',
    label: 'unblock checkAllLoaded by setting mxWinLoaded',
  },
]

for (const { needle, replacement, label } of targets) {
  if (!bootstrap.includes(needle)) {
    console.error(`[copy-drawio] FAILED: pattern not found for "${label}"`)
    console.error('  searched for (raw):', JSON.stringify(needle))
    process.exit(1)
  }
}

let patched = bootstrap
for (const { needle, replacement, label } of targets) {
  patched = patched.replace(needle, replacement)
  console.log(`[copy-drawio] patched: js/bootstrap.js (${label})`)
}
writeFileSync(bootstrapPath, patched, 'utf8')

console.log(`[copy-drawio] done. assets at: ${DST}`)
